### ISSUE TITLE
[pakage.joson] Unnecessary use of babel 

### ISSUE THREAD

**Issue by dipto0321** [inhaq/StoreCMS#6]
I am pretty sure you used create-react-app to build that project. 🙂 . And it will already handle all the necessary packages for `babel` via `react-script`. So can you explain to me why you need to put [this ](https://github.com/inhaq/StoreCMS/blob/458246ba6fa93167f7db8ed4410ddd5aee441344/package.json#L34-L37) in `package.json`? I removed this and I tried to play with your app and there was no issue.

So, if there was no valid reason to add this in package.json then you can remove it.

**Comment by dipto0321** [comment]
> I'm having errors without them since I've multiple versions of each package installed.

I didn't get that? Why you need multiple versions of each package? And how it's work in my case when I deleted this? 🙂

**Comment by inhaq** [comment]
I've multiple version of node and mostly using global packages instead of local ones.

**Comment by dipto0321** [comment]
Okay. Got it
