### ISSUE TITLE
[BooksForm] Error Handling

### ISSUE THREAD

**Issue by dipto0321** [inhaq/StoreCMS#7]
I liked that you included error handling but there is a proper way to do this with react. You can check out this [article ](https://flaviocopes.com/react-handle-errors/) to know more about them. Also, you can[ check the official one also ](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html) 🙂

**Comment by inhaq** [comment]
Hi @dipto0321, which error we're talking about here?

**Comment by dipto0321** [comment]
I am talking about [this ](https://github.com/inhaq/StoreCMS/blob/458246ba6fa93167f7db8ed4410ddd5aee441344/src/containers/BooksForm.js#L30-L33). Again, if you think that this is the proper way to handling error then explain to me why so that I can also understand and clear my concept 🙂 

Thanks

**Comment by inhaq** [comment]
That's not the right way to handle it. We just put it for our self. It's not required in guidelines though.

**Comment by dipto0321** [comment]
This is the final project and thus we are using a higher standard for the students. Error handling is a basic concept in React and if we didn't intend to do it right then it would have been better than we didn't include this feature.

**Comment by inhaq** [comment]
I understand and I just put it for my own sake. I just want it to be there.

**Comment by zlayabekrija** [comment]
Ad acta
