### ISSUE TITLE
[BooksForm][render] No need of using bind in handleSubmit 

### ISSUE THREAD

**Issue by dipto0321** [inhaq/StoreCMS#8]
https://github.com/inhaq/StoreCMS/blob/458246ba6fa93167f7db8ed4410ddd5aee441344/src/containers/BooksForm.js#L53

Why binding an event handler directly in the element using it is bad:

1. The method gets redeclared every time when a books form is created an instance
2. React already gave us an easy way to declare and call our event handlers. This doesn't require the `bind` keyword at all

You can read [this ](https://codeburst.io/use-class-properties-to-clean-up-your-classes-and-react-components-93185879f688) and [this](https://medium.com/@jacobworrel/babels-transform-class-properties-plugin-how-it-works-and-what-it-means-for-your-react-apps-6983539ffc22).

**Comment by inhaq** [comment]
I don't find articles helpful. What are you suggesting for removing `bind` from `button`? A snippet will be helpful.

**Comment by dipto0321** [comment]
Hi @inhaq ,

> What are you suggesting for removing bind from the button? 
Yes. I am. Why? if you read those article properly then you can understand 🙂 Also, I gave you two point on that.

Thanks

**Comment by inhaq** [comment]
I read those articles properly and I still didn't get it. I'm asking for the snippet. If you know how to change it, kindly share the updated code as I'm not able to do it different way.

**Comment by dipto0321** [comment]
Simply remove 'bind(this)` that's it.

**Comment by inhaq** [comment]
[Here](https://github.com/gaearon/overreacted.io/blob/master/src/components/Toggle.js) you go, just want to let you know he's the founder of redux and core contributor of react team, currently hired by facebook. If he's using bind then i can't see any problem using it.

**Comment by zlayabekrija** [comment]
Ad acta
