### ISSUE TITLE
[BookList] Unnecessary and redundant function declarations

### ISSUE THREAD

**Issue by dipto0321** [inhaq/StoreCMS#9]
https://github.com/inhaq/StoreCMS/blob/458246ba6fa93167f7db8ed4410ddd5aee441344/src/containers/BooksList.js#L19-L25

This is the better way to write this. No need those functions declarations.

```javascript
const { remove, changeFilter } = props;
  return (
    <div className="bookList">
      <CategoryFilter onFilterChange={e => changeFilter(e.target.value)} />
      {showBooks.map(book => {
        return <Book key={book.id} book={book} onRemove={() => remove(book)} />;
      })}
    </div>
  );
```

**Comment by inhaq** [comment]
I don't think this is a necessary update.

**Comment by dipto0321** [comment]
Why do you think that is an unnecessary update? When you can do the same thing without creating extra class properties. I would love to know. 🙂

**Comment by inhaq** [comment]
C'mon these aren't extra class properties, you're declaring it on component, I'm declaring it outside.

**Comment by dipto0321** [comment]
As you see in the code snippet I provided it was unnecessary to declare another `handleFilterChange` and `handleRemoveBook` functions outside. Again I would like to refer you back to my statement about this project being the final project and the standards we are using in reviewing this project is much higher. The finalized review guidelines will definitely include this.

**Comment by inhaq** [comment]
Well, I don't know the standards you guys are up to. This is the best I can do. I'm not going to change it just because you think that's a better way to do so. I don't change my thinking unless there is some valid resource, reference, research paper or some other guidelines.

**Comment by zlayabekrija** [comment]
Ad acta
